### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by SuperYYT** [ST-Apps/CS2-ExtendedRoadUpgrades#10]
We introduced this mod to the Chinese community! There are also members who have made a Chinese version. But third-party translations are always not timely. Is there any opportunity to add multi-language support so that we can contribute to the localization of this mod?

**Comment by ST-Apps** [comment]
The support is already there actually, I'm just missing the strings :)

https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/blob/a31e683fd6385f484584928b2038d9418e061125/Data/ExtendedRoadUpgrades.cs#L22-L33

You can start a PR by providing the right entries for your locale, if you're not familiar with C# code you can just add the strings in a comment here and I'll try to add them to the next release.
