### ISSUE TITLE
Issue with Retaining Walls

### ISSUE THREAD

**Issue by JEBSCS** [ST-Apps/CS2-ExtendedRoadUpgrades#32]
As you can see in the picture below once I reloaded my save game the corners did that. I tried to fix it by using the terraforming tools, but it did not work.

![Screenshot 2023-12-03 221328](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/54189691/8434e2a5-1f3c-43df-a681-bb7527b06213)

**Comment by MMichalec** [comment]
I can add some additional info to this issue - I have noticed it happening suddenly all over the city, not only on corners - on nodes connected too. I can fix those issue by some additional manipulations (like re-applying walls, landscapign etc) easly.

But I can't save those changes - if I fix roads, save and then close the game (like whole app and go to dektop) and reload save those cracks will be back. But If I save game and won't close whole app (like go to menu or just load another save) the cracks are not returning. It's like restarting the game is an issue.

![image_2024-01-04_134144555-min](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/62188516/73a98254-4845-4223-a679-1124a4aec3f1)

**Comment by ST-Apps** [comment]
Closing because it's the same issue as #33, let's continue the discussion there and thanks for the report!
