### ISSUE TITLE
Upgrades not working properly

### ISSUE THREAD

**Issue by SumNutz** [ST-Apps/CS2-ExtendedRoadUpgrades#8]
mod won't actually manipulate the roads and surrounding terrain as expected, instead all of the three options act the same as the vanilla grass strip option, as well as having the same thumbnail

![image](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/46006004/43b809c4-356f-4fd4-8103-a52ec1c6e782)

tested on new game
running the 1.0.2 BepInEx 6 version of extended road upgrades with no other mods loaded at the moment
running BepInEx 6.0.0 as shown in the output log below:
[LogOutput.log](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/files/13462762/LogOutput.log)

showcase video:

https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/46006004/a105d1a7-d625-48dd-b26d-7897d5daa205

**Comment by thx114** [comment]
+1  
![b0087e7927c29d85f53d8052822cc359](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/52259890/106a5358-43f4-4d56-a8f4-af1dbf751a93)

it not working on 1.1/ 1.2 / BepInEx5/BepInEx6/BepInEx-Unity.Mono-win-x64-6.0.0-be.674+82077ec / [zh-CNversion](https://www.cslbbs.net/resources/extendedroadupgrades.55/)

**Comment by ST-Apps** [comment]
Should've been fixed with #9, can you please download v1.1.1 from the releases page and report back here?
@SumNutz @thx114

**Comment by SumNutz** [comment]
> Should've been fixed with #9, can you please download v1.1.1 from the releases page and report back here? @SumNutz @thx114

sure thing

**Comment by SumNutz** [comment]
@ST-Apps tested on new game with other mods installed and it worked as intended now

here's a screenshot with all upgrades applied at different sections
![image](https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/assets/46006004/b2de5929-05ae-42a9-90f8-2944cac872b8)
